### PR TITLE
groonga-release: Add support for AlmaLinux 9

### PR DESCRIPTION
**Pull request by HashidaTKS**
groonga-release: Add support for AlmaLinux 9

### CODE REVIEW

**Comment by HashidaTKS** [comment]
@kou @komainu8 

Would you please review this?

**Comment by komainu8** [comment]
Did you confirm a result of build with `rake yum:build ...`?

**Comment by HashidaTKS** [comment]
> Did you confirm a result of build with rake yum:build ...?

Yes, but honestly, I don't determine whether an artifact file is correct or not...

Terminal log: [terminal.log.gz](https://github.com/groonga/packages.groonga.org/files/9625830/terminal.log.gz)
Artifact: [groonga-release-2022.3.6.tar.gz](https://github.com/groonga/packages.groonga.org/files/9625831/groonga-release-2022.3.6.tar.gz)

**Comment by HashidaTKS** [comment]
[almalinux.tar.gz](https://github.com/groonga/packages.groonga.org/files/9625950/almalinux.tar.gz)

**Review by komainu8 — APPROVED** [review]
+1

**Comment by kou** [comment]
We can verify the artifact on AlmaLinux 9 with the following:

1. `dnf install -y groonga-release.rpm`
2. `dnf repolist` includes `groonga-almalinux` and doesn't include any other `groonga-*`
3. `dnf update` doesn't report any error for `groonga-almalinux`

**Pull request merged**
