### PR TITLE
mecab: split directory every target OSes

### PR DESCRIPTION
**Pull request by komainu8**
Because the version of MeCab for AlmaLinux 8 different the version of MeCab for Amazon Linux 2.

### CODE REVIEW

**Comment by kou** [comment]
Should we remove them?

* https://github.com/groonga/packages.groonga.org/pull/30/files#diff-62eca481e4912d74f6e294db1bf06234e8016e35fd120aa9b3b34b539cff6be0
* https://github.com/groonga/packages.groonga.org/pull/30/files#diff-efee6605f3a965d053923ec9a2dbe8a39e6adb5221c8ed192b99a4cb63a0dffb
* https://github.com/groonga/packages.groonga.org/pull/30/files#diff-71a5d21369c5ed01cef247a6e040d6748473df3a813e24545071ac2979339953

**Comment by komainu8** [comment]
Ah...sorry.

I removed them.

**Comment by kou** [comment]
Could you put all packages in top directory instead of `mecab/` sub directory like the current `mecab-almalinux-9`?

**Comment by komainu8** [comment]
I put all packages related mecab in the top directory.

**Pull request merged**
